/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef DELTAVPARSER_PRIVATE_H
#define DELTAVPARSER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.4.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	4
#define VER_BUILD	0
#define COMPANY_NAME	"Claudio Lopez"
#define FILE_VERSION	"1.0.4.0"
#define FILE_DESCRIPTION	"DeltaVParser"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"DeltaVParser"
#define PRODUCT_VERSION	"1.0.4.0"

#endif /*DELTAVPARSER_PRIVATE_H*/
